export const RESTORE_STATE = 'RESTORE_STATE';
export const SEARCH_VIDEOS = 'SEARCH_VIDEOS';
export const GET_VIDEO_BY_ID = 'GET_VIDEO_BY_ID';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const CLEAR_FAVORITES = 'CLEAR_FAVORITES';
